### ISSUE TITLE
feat: configure retries, delays, policies for knative-function

### ISSUE THREAD

**Issue by metacoma** [mindwm/mindwm-gitops#105]
```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: with-dead-letter-sink
spec:
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: example-sink
    backoffDelay: <duration>
    backoffPolicy: <policy-type>
    retry: <integer>
```
