### ISSUE TITLE
feat: build mindwm function inside k8s kubernetes

### ISSUE THREAD

**Issue by metacoma** [mindwm/mindwm-gitops#130]
- [x] tekton pipelines
- [x] internal image registry
- [x] image build
- [x] image push

**Comment by metacoma** [comment]
internal-registry done #134 
tekton-pipelines done #131 

tekton-pipelines example:
```YAML
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: mindwm-function-build-run
spec:
  pipelineSpec:
    workspaces:
    - name: build
    - name: source
    tasks:
      - name: copy
        taskSpec:
          steps:
          - name: copy-app-files
            image: busybox
            script: |
              #!/bin/sh
              cp -vLr /workspace/source/* /workspace/build
        workspaces:
          - name: source
            workspace: source
          - name: build
            workspace: build

      - name: resolve-host
        runAfter:
          - copy
        taskSpec:
          results:
            - name: host-ip
              description: "Resolved IP address of zot-int.zot.svc.cluster.local"
          steps:
            - name: get-host-ip
              image: nicolaka/netshoot:latest
              script: |
                #!/bin/sh
                echo "Resolving IP for zot-int.zot.svc.cluster.local..."
                IP=$(getent hosts zot-int.zot.svc.cluster.local | awk '{ print $1 }')
                echo "Resolved IP: $IP"
                echo -n "$IP" > $(results.host-ip.path)

      - name: buildpack
        runAfter: 
          - resolve-host
        params:
          - name: REGISTRY_IP
            value: $(tasks.resolve-host.results.host-ip)
        taskSpec:
          steps:
            - name: pack-build
              env:
                - name: CNB_INSECURE_REGISTRIES 
                  value: zot-int.zot;zot.zot.svc.cluster.local
              image: buildpacksio/pack:latest
              workingDir: /workspace/build
              command: 
                - pack
                - build
                - $(params.REGISTRY_IP):5000/test3:latest
                #- --buildpack-registry
                #- zot.zot:5000
                - --builder
                - paketobuildpacks/builder-jammy-tiny
                - --workspace
                - /workspace/build
                - --docker-host=inherit
                - --publish
              securityContext:
                privileged: true
                runAsUser: 0
                runAsGroup: 0
                allowPrivilegeEscalation: true
                capabilities:
                  add: ["ALL"]
              volumeMounts:
                - name: docker-socket
                  mountPath: /var/run/docker.sock
          volumes:
              - name: docker-socket
                hostPath:
                  path: /var/run/docker.sock
                  type: Socket

        workspaces:
          - name: build
            workspace: build
  workspaces:
  - name: build
    subPath: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: source
    configMap:
      name: test
```

apply + logs
```
kubectl delete -f mindwm-function-build.yaml
kubectl apply -f mindwm-function-build.yaml
tkn pr logs -f mindwm-function-build-run
```
