### ISSUE TITLE
feat: create separate Node-RED tabs for host, user, and context XRDs

### ISSUE THREAD

**Issue by metacoma** [mindwm/mindwm-gitops#268]
- [x] add crossplane-http provider to kcl-lang/modules closed by https://github.com/kcl-lang/modules/pull/292

```gherkin
@mindwm_crd_resources
Feature: MindWM Custom kubernetes resources 
...
Scenario Outline: Check that Node-RED contains the expected tabs
  Then Node-RED should have a tab named "<tab name>" in context "context_name"

Examples:
  | tab name      |
  | context-cyan  |
  | user-alice    |
  | host-laptop   |
```

**Comment by metacoma** [comment]
crossplane-http kcl module https://github.com/kcl-lang/modules/pull/292

**Comment by metacoma** [comment]
```yaml
apiVersion: http.crossplane.io/v1alpha2
kind: DisposableRequest
metadata:
  name: test
spec:
  deletionPolicy: Delete
  forProvider:
    body: '{"id": "context-cyan", "type": "tab", "label": "context-cyan"}'
    headers:
      Content-type:
      - application/json
    method: POST
    url: https://node-red.cyan.mindwm.local
  managementPolicies:
  - '*'
---
apiVersion: http.crossplane.io/v1alpha2
kind: DisposableRequest
metadata:
  name: test
spec:
  deletionPolicy: Delete
  forProvider:
    body: '{"id": "user-bob", "type": "tab", "label": "user-bob"}'
    headers:
      Content-type:
      - application/json
    method: POST
    url: https://node-red.cyan.mindwm.local
  managementPolicies:
  - '*'
---
apiVersion: http.crossplane.io/v1alpha2
kind: DisposableRequest
metadata:
  name: test
spec:
  deletionPolicy: Delete
  forProvider:
    body: '{"id": "user-bob-host-workstation", "type": "tab", "label": "user-bob-host-workstation"}'
    headers:
      Content-type:
      - application/json
    method: POST
    url: https://node-red.cyan.mindwm.local
  managementPolicies:
  - '*'
```
