### ISSUE TITLE
feat: trigger to pass events from Knative Eventing to the client nats topic

### ISSUE THREAD

**Issue by metacoma** [mindwm/mindwm-gitops#60]
Must be part of managed crossplane resources
```yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: {{ host }}-trigger-name
  namespace: context-{{ context_name }}
spec:
  broker: context-broker-{{ context_name }}
  filter: {}
  filters:
    - cesql: "source LIKE 'graph.%'"
  subscriber:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: {{ host }}-broker
      namespace: user-{{ user }}
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: context-broker-{{ context }}-dead-letter
```
