### ISSUE TITLE
feat: add environment variables from the k8s configmap

### ISSUE THREAD

**Issue by metacoma** [mindwm/mindwm-gitops#73]
For each  knative function, add environment variables from the `context-config` configmap:

changes in container deployment
```
 envFrom:
    - configMapRef:
        name: context-config
```
example context-config 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: context-config
data:
  MINDWM_CONTEXT_NAME: purple
  NEO4J_URI=bolt://neo4j:7878
```

**Comment by metacoma** [comment]
Example knative configuration
```
apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  name: values-from-example
spec:
  template:
    spec:
      containers:
      - image: example.com/an/image
        envFrom:
        - configMapRef:
            name: example-configmap
        - secretRef:
            name: example-secret
```
