### ISSUE TITLE
feat: add ping knative function

### ISSUE THREAD

**Issue by metacoma** [mindwm/mindwm-gitops#93]

**Comment by metacoma** [comment]
trigger:
```
  filters:
  - all:
    - exact:
        type: org.mindwm.v1.iodocument
    - prefix:
        subject: '#ping'
```
