### ISSUE TITLE
feat: add kafka-cdc knative function

### ISSUE THREAD

**Issue by metacoma** [mindwm/mindwm-gitops#94]

**Comment by metacoma** [comment]
trigger: 
```yaml
  filters:
  - all:
    - exact:
        type: dev.knative.kafka.event
    - not:
        prefix:
          source: org.mindwm
```
